import { Container, UsageContext } from './containers.types'

export const containerMock: Container = {
	path: 'accounts/123456789/containers/987654321',
	accountId: '123456789',
	containerId: '987654321',
	name: 'Test Container',
	domainName: ['example.com', 'www.example.com'],
	publicId: 'GTM-XXXXX',
	tagIds: ['GTM-XXXXX'],
	features: {
		supportUserPermissions: true,
		supportEnvironments: true,
		supportWorkspaces: true,
		supportGtagConfigs: true,
		supportBuiltInVariables: true,
		supportClients: true,
		supportFolders: true,
		supportTags: true,
		supportTemplates: true,
		supportTriggers: true,
		supportVariables: true,
		supportVersions: true,
		supportZones: true,
		supportTransformations: true,
	},
	notes: 'This is a test container',
	usageContext: [UsageContext.WEB],
	fingerprint: '1234567890',
	tagManagerUrl: 'https://tagmanager.google.com/#/container/accounts/123456789/containers/987654321',
	taggingServerUrls: ['https://example.com/gtm'],
}

export const mobileContainerMock: Container = {
	path: 'accounts/123456789/containers/123123123',
	accountId: '123456789',
	containerId: '123123123',
	name: 'Mobile App Container',
	publicId: 'GTM-YYYYY',
	tagIds: ['GTM-YYYYY'],
	features: {
		supportUserPermissions: true,
		supportEnvironments: true,
		supportWorkspaces: true,
		supportGtagConfigs: false,
		supportBuiltInVariables: true,
		supportClients: false,
		supportFolders: true,
		supportTags: true,
		supportTemplates: true,
		supportTriggers: true,
		supportVariables: true,
		supportVersions: true,
		supportZones: false,
		supportTransformations: false,
	},
	notes: 'Mobile app tracking container',
	usageContext: [UsageContext.ANDROID, UsageContext.IOS],
	fingerprint: '0987654321',
	tagManagerUrl: 'https://tagmanager.google.com/#/container/accounts/123456789/containers/123123123',
}

export const serverContainerMock: Container = {
	path: 'accounts/123456789/containers/456456456',
	accountId: '123456789',
	containerId: '456456456',
	name: 'Server-side Container',
	publicId: 'GTM-ZZZZZ',
	tagIds: ['GTM-ZZZZZ'],
	features: {
		supportUserPermissions: true,
		supportEnvironments: true,
		supportWorkspaces: true,
		supportGtagConfigs: false,
		supportBuiltInVariables: true,
		supportClients: true,
		supportFolders: false,
		supportTags: true,
		supportTemplates: true,
		supportTriggers: true,
		supportVariables: true,
		supportVersions: true,
		supportZones: false,
		supportTransformations: true,
	},
	notes: 'Server-side tagging container',
	usageContext: [UsageContext.SERVER],
	fingerprint: '5555555555',
	tagManagerUrl: 'https://tagmanager.google.com/#/container/accounts/123456789/containers/456456456',
	taggingServerUrls: ['https://gtm-server.example.com', 'https://gtm-server-backup.example.com'],
}
